### ISSUE TITLE
ESLint checking for Ember.js

### ISSUE THREAD

**Issue by Turbo87** [emberjs/emberjs-build#161]
I started replacing JSHint and JSCS with ESLint in the Ember.js repo in https://github.com/emberjs/ember.js/pull/13549. The next step would be to make it part of the QUnit test suite and I assume that I need to modify this repo for that. Since I'm not that familiar with the whole build process yet it would be awesome to get some pointers on how to do this properly. 

/cc @rwjblue @stefanpenner @krisselden

**Comment by stefanpenner** [comment]
can you enumerate any specific questions I can answer?

**Comment by Turbo87** [comment]
so from what I can tell there are envvars to disable jshint and JSCS. Should I just create another one for eslint or would it have to be more sophisticated? What should the default for that be? Should I disable jshint and JSCS once eslint exists?

**Comment by rwjblue** [comment]
> Should I just create another one for eslint

Yep, and when we update Ember, make sure to update the comment on the top of `ember-cli-build.js` to indicate how to disable it.

> What should the default for that be

The same as the DISABLE_JSHINT and DISABLE_JSCS ones.  They should be falsey by default (so that eslint runs if no ENV vars are provided).

> Should I disable jshint and JSCS once eslint exists?

Yes, remove both JSHint and JSCS (will be a "major" version bump for this lib).
